[RFC] add deleteGame
kuznetsov0209/kicker-backend pull request #2
Opened 2019-10-22 18:11 UTC by igooooood

![https://trello.com/c/DUtsirCA/17-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-api-%D0%B4%D0%BB%D1%8F-%D1%83%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8%D0%B3%D1%80%D1%8B]

2019-10-23 07:55 UTC, kuznetsov0209 requested changes

2019-10-23 07:55 UTC, kuznetsov0209 commented on README.md
> +
Изменений, не касающихся задачи, не должно быть в PR

2019-10-23 07:55 UTC, kuznetsov0209 commented on app/gamesModule.js
> +}
Game содержит связи не только с моделью Goal, но и с моделью GamePlayer. В твоем варианте игра не удалиться, т.к. к моменту выполнения `db.Game.destroy({ where: { id: gameId } });` будут существовать записи из таблицы GamePlayers, который ссылаются на эту игру.

2019-10-23 07:55 UTC, kuznetsov0209 commented on routers/apiGamesRouter.js
> +      ctx.body = { error: "что-то пошло не так" };
У Koa есть специальный хэлпер для проброса ошибок — давай использовать его https://github.com/koajs/koa/blob/master/docs/api/context.md#ctxthrowstatus-msg-properties

2019-10-23 20:11 UTC, igooooood commented on app/gamesModule.js
> +}
Когда я пытался удалить игру, падала ошибка, в которой было сказано то о чём ты говоришь выше но касательно `Goals`.  После того как я написал данную строку `db. Goal.destroy({ where: { id: gameId } });` игры начали удаляться.

Сейчас таблица `GamePlayers` пустая и видимо поэтому ни какой ошибки нет. Но я добавил удаление и оттуда)

2019-10-23 20:33 UTC, igooooood commented on README.md
> +
Немного неправильно сделал предыдущий PR. сделал правку прямо в develop. И до апрува ответвился от неё же, забрав с собой изменения. Поэтому так вышло. Сейчас я убрал изменения как ты и написал, таким образом образовав конфликт.

2019-10-24 08:03 UTC, kuznetsov0209 requested changes
Нужно подмержить master в свою ветку и зарезолвить конфликты.

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

2019-10-24 08:03 UTC, kuznetsov0209 commented on routers/apiGamesRouter.js
> +      ctx.throw(400, "something went wrong");
Давай обойдемся без сообщения, раз никакой пользы оно все равно не несет :)

2019-10-24 08:16 UTC, igooooood commented on routers/apiGamesRouter.js
> +      ctx.throw(400, "something went wrong");
окей
``

2019-10-24 08:33 UTC, merged