Add API method recalculate statistic
kuznetsov0209/kicker-backend pull request #5
Opened 2019-11-18 12:45 UTC by DmitryDoskolovich

2019-11-18 12:48 UTC, DmitryDoskolovich commented on app/ratingModule.js
> +    if (game.Users && game.Users.length === 4) {
Проверка на то, что игра валидная. Функция addGame принимает игру, в которой должно быть 4 игрока, а в базе есть игра, где 3 игрока.

2019-11-18 13:47 UTC, akuznetsov-md commented on app/ratingModule.js
> +    if (game.Users && game.Users.length === 4) {
Вынеси в отдельную функцию модуля gameModule — `isGameValid`

2019-11-20 12:01 UTC, akuznetsov-md requested changes

2019-11-20 12:01 UTC, akuznetsov-md commented on app/ratingModule.js
> +    updateStatus("IN PROGRESS", moment());
Использование moment здесь избыточно. То же самое можно сделать при помощи стандартного Date

2019-11-21 07:57 UTC, akuznetsov-md commented on app/usersModule.js
> +async function updateUser(userObj, transaction) {
В этом варианте сломается метод /api/users/:userId.

2019-11-21 08:02 UTC, akuznetsov-md commented on app/usersModule.js
> +async function updateUser(userObj, transaction) {
Добавь третим аргументом объект params, который будет принимать transaction. Это будет компромиссным вариантом между "все аргументы в виде объекта" и "все аргументы отдельно". Получится, что все _опциональные_ аргументы будут пробрасываться  в виде объекта, т.е. именованными и легко расширяемыми.

2019-11-21 08:03 UTC, akuznetsov-md commented on app/usersModule.js
> +async function updateUser(userObj, transaction) {
Аналогичный подход следует применить и в других методах, где тебе сейчас необходима transaction

2019-11-21 09:40 UTC, akuznetsov-md commented on app/gamesModule.js
> +      : undefined
Чтобы не делать таких проверок, можно назначить дефолтное значение аргументу:
```
async function getGame(gameId, params = {}) {
  ...
}
```

2019-11-21 10:55 UTC, merged